<<<<<<< HEAD
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: mvn clean install exec:java -Dexec.mainClass="com.lambdatest.BasicAuthentication" -Dexec.classpathScope=test -e
=======
# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: mvn install -Dsuite=parallel.xml # runs during prebuild
    command: echo 'Please check your test on https://automation.lambdatest.com/'
>>>>>>> branch 'master' of https://github.com/kanakaGitPractice/LambdaTest.git
